version: 2

sources:
    - name: jaffle
      database: raw
      schema: jaffle_shop
      tables:
        - name: orders
          columns:
            - name: id
              tests:
                - not_null
                - unique
        - name: customers
    - name: stripe
      database: raw
      schema: stripe
      tables: 
        - name: payments