version: 2

sources:
    - name: jaffle
      database: raw
      schema: jaffle_shop
      tables:
        - name: orders
        - name: customers
    - name: stripe
      database: raw
      schema: stripe
      tables:
        - name: payments